### ISSUE TITLE
Performance issues after a submenu is opened

### ISSUE THREAD

**Issue by kemayo** [p3lim-wow/LibDropDown#21]
**Describe the bug**
I did some speculative porting of my addon's dropdown to this (for taint reasons, naturally), and I observed some performance issues. Specifically, something about mousing over the lines of the open dropdown causes noticeable framerate stuttering. This doesn't seem to occur until after I've opened a submenu that itself contains a line with a checkbox, though the stutter spreads to the parent menu as well (but I might be over-indexing on limited results here).

**How to reproduce**
Create a menu with a submenu. Open the submenu. Mouse over the items in either menu, and watch for framerate stutters.

**What did you expect?**
No framerate issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/2187/192417604-7b15442b-3204-4f3a-9bd3-5d7415de18bc.png)

**Comment by kemayo** [comment]
Maybe related, maybe not, note that the submenu's width is off -- the checkboxes overlap the text.

**Comment by kemayo** [comment]
If you're curious, the exact code is in overlay.lua in this branch commit: https://github.com/kemayo/wow-handynotes-handler/commit/ab91b7045234df8acce9e8d21dec0085a300b7b1

**Comment by p3lim** [comment]
I'll take a look, thanks.

> Maybe related, maybe not, note that the submenu's width is off -- the checkboxes overlap the text.

Most likely not related, but I'll fix it nonetheless.

**Comment by p3lim** [comment]
Found the cause, it's the auto-hide/show timers.

**Comment by p3lim** [comment]
Give that a whirl, I haven't bumped the version yet

**Comment by p3lim** [comment]
I used your codebase to debug this, and I found that you set the scale of the dropdown to 80%, is there a particular reason for this?

**Comment by kemayo** [comment]
I'm away from my desktop right now so I can't immediately check it out myself.

As I recall I set the scale because it was notably bigger than the equivalent Blizzard dropdown in that situation. Possibly this is because I was creating it at a time when the map pins it'd be coming from didn't yet exist, and it looked like setting the menu's parent was only possible on initial creation, unlike when toggling the blizzard dropdown. I didn't dig too hard into a better parent, since setting the scale achieved about what I wanted.

**Comment by kemayo** [comment]
Hm, actually, looking at my code again it's for the one that doesn't need to be reparented. Probably an issue with the parent scale somewhere with the button I'm making that triggers it, ultimately, then.

**Comment by p3lim** [comment]
I also added this for you: https://github.com/p3lim-wow/LibDropDown/commit/f1cc7d2e41e56bfcd51ba9b31560406a81dd9f36
