### ISSUE TITLE
Add the ability to change the checked state of a related line and have the display update"refresh" an open menu

### ISSUE THREAD

**Issue by jnwhiteh** [p3lim-wow/LibDropDown#27]
I have a submenu that has two options "hovercast" and "global" that need to be mutually exclusive. When I select one, I need the other one to be disabled just to prevent misconfiguration. This isn't possible without custom code at the moment.

I can update the checked state of the clicked line, but that doesn't cause an update to the other line. I could reorganise the code and then try to manually iterate over all open lines (or find the line) to trigger an update. It would be nice to add a feature that allows me to "refresh" an open dropdown or submenu.

**Comment by p3lim** [comment]
@jnwhiteh let me know if this covers your needs

**Comment by p3lim** [comment]
Example on how I used it in LibEditMode: https://github.com/p3lim-wow/LibEditMode/commit/6f7238048cfe618239038cdaa60f445e2a39f7d1
